format: progress

ignore:
  - './**/*':
    - Style/StringLiterals
    - Layout/ClosingHeredocIndentatio
    - Layout/SpaceInsideStringInterpolation
    - Layout/IndentHeredoc
    - Style/SpecialGlobalVars
    - Style/HashSyntax
    - Layout/ClosingHeredocIndentation
