version: '2'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/docker-sinatra
    environment:
      - RACK_ENV=development
    command: ["/home/circleci/sinatra-sandbox/start_service.sh"]
