version: '2'
services:
  app:
    image: tinisi/agent-0028-sinatra-sandbox:${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}
    build: .
    ports:
      - "80:80"
    environment:
      - RACK_ENV=production
    command: ["/var/www/docker-sinatra/start_service.sh"]
