version: '2'
services:
  app:
    # image: tinisi/agent-0028-sinatra-sandbox:bootstrap-n-setup-build-18-a7e408b8163cdfa13704fe4754e1a26d9896d624
    image: tinisi/agent-0028-sinatra-sandbox:${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}
    ports:
      - "80:80"
    environment:
      - RACK_ENV=production
    command: ["/var/www/docker-sinatra/start_service.sh"]
