version: 2
jobs:
  build:
    working_directory: ~/sinatra-sandbox
    docker:
      - image: circleci/ruby:2.3.5-jessie
        environment:
          RACK_ENV: production
    steps:
      - setup_remote_docker

      - checkout

      - run: docker-compose --file docker-compose-build.yml up -d

      - run: docker-compose --file docker-compose-build.yml exec app rspec spec

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker push tinisi/agent-0028-sinatra-sandbox:${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}
