version: 2
jobs:
  build:
    working_directory: ~/sinatra-sandbox
    docker:
      - image: circleci/ruby:2.3.5-jessie
        environment:
          RACK_ENV: production
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build image and start app
          command: docker-compose --file docker-compose-build.yml up -d

      - run:
          name: Unit tests
          command: docker-compose --file docker-compose-build.yml exec app rspec spec/unit

      - run:
          name: Request tests
          command: docker-compose --file docker-compose-build.yml exec app rspec spec/request

      - run:
          name: Log in to Dockerhub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Push image to Dockerhub
          command: docker push tinisi/agent-0028-sinatra-sandbox:${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}
