version: 2
jobs:
  test-n-build:
    working_directory: ~/sinatra-sandbox
    docker:
      - image: circleci/ruby:2.3.5-jessie
        environment:
          RACK_ENV: production
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build image and start app
          command: docker-compose --file docker-compose-build.yml up -d

      - run:
          name: Unit tests
          command: docker-compose --file docker-compose-build.yml exec app rspec spec/unit

      - run:
          name: Request tests
          command: docker-compose --file docker-compose-build.yml exec app rspec spec/request

      - run:
          name: Log in to Dockerhub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Push image to Dockerhub
          command: docker push tinisi/agent-0028-sinatra-sandbox:${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}

  deploy:
    working_directory: ~/sinatra-sandbox
    docker:
      - image: circleci/python:2.7.15-jessie
    steps:
      - add_ssh_keys

      - checkout

      - run: ssh-keyscan trinity.tinisi.com >> /home/circleci/.ssh/known_hosts

      - run: git clone git@github.com:tinisi/grosgrain.git /home/circleci/grosgrain

      - run: cd ~/grosgrain/fabric && pipenv install --ignore-pipfile

      - run: cd ~/grosgrain/fabric && pipenv run fab docker_compose_deploy:"${CIRCLE_BRANCH}-build-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1}","/home/circleci/sinatra-sandbox/docker-compose-deploy.yml","sinatra-sandbox" --hosts=nexus.tinisi.com --user=tinisi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-n-build
      - deploy:
          requires:
            - test-n-build
          filters:
            branches:
              only: add-cd
