version: 2
jobs:
  build:
    working_directory: ~/sinatra-sandbox
    docker:
      - image: circleci/ruby:2.3.5-jessie
        environment:
          RACK_ENV: production
    steps:
      - setup_remote_docker
      - checkout

      # # Restore bundle cache
      # - type: cache-restore
      #   key: sinatra-demo-{{ checksum "Gemfile.lock" }}

      # # Bundle install dependencies
      # - run: bundle install --path vendor/bundle

      # # Store bundle cache
      # - type: cache-save
      #   key: sinatra-demo-{{ checksum "Gemfile.lock" }}
      #   paths:
      #     - vendor/bundle

      - run: docker-compose --file docker-compose-build.yml up -d

      - run: docker-compose --file docker-compose-build.yml exec app rspec spec

      - run: docker-compose --file docker-compose-build.yml down

      # Save artifacts
      # - type: store_test_results
      #   path: /tmp/test-results